export interface MonthlyRecord {
  month: string;
  generation: number;
  revenue: string;
  payout: string;
  status: string;
}

export interface Translation {
  nav: {
    home: string;
    about: string;
    partners: string;
    investors: string;
    services: string;
    solar3d: string;
    contact: string;
    investorZone: string;
  };
  hero: {
    badge: string;
    slogan: string;
    subSlogan: string;
    desc: string;
    ctaInvestors: string;
    ctaPartners: string;
    cta3D: string;
    activeProjectTitle: string;
    activeProjectSubtitle: string;
    statCapacityVal: string;
    statCapacityLabel: string;
    statTermVal: string;
    statTermLabel: string;
    statTariffVal: string;
    statTariffLabel: string;

    systemStatus: string;
    stableGrid: string;
  };
  about: {
    badge: string;
    title: string;
    subTitle: string;
    regionText: string;
    introP1: string;
    introP2: string;
    japanUzPartnerTitle: string;
    japanUzPartnerDesc: string;
    companyDetailsTitle: string;
    companyDetails: { label: string; value: string }[];
    missionTitle: string;
    missionDesc: string;
    visionTitle: string;
    visionDesc: string;
    ppaTitle: string;
    ppaDesc: string;
    ppaBenefits: { title: string; desc: string }[];
    serviceChainTitle: string;
    serviceChainDesc: string;
    serviceChain: string[];
    whyTitle: string;
    whyDesc: string;
    whyPoints: { title: string; desc: string }[];
    valuesTitle: string;
    values: { title: string; desc: string }[];
    currentProjectTitle: string;
    currentProjectBadge: string;
    currentProjectDesc: string;
    currentProjectSpecs: { label: string; value: string }[];
    teamBadge?: string;
    teamTitle?: string;
    teamDesc?: string;
    teamMembers?: {
      name: string;
      role: string;
      image: string;
      fallbackImage?: string;
    }[];
  };
  partners: {
    badge: string;
    title: string;
    desc: string;
    partnersList: {
      id: string;
      name: string;
      badge: string;
      description: string;
      details: { label: string; value: string }[];
    }[];
    ecosystemTitle: string;
    ecosystemDesc: string;
    ecosystemHeaders: {
      partner: string;
      role: string;
    };
    ecosystemRows: {
      partner: string;
      role: string;
    }[];
    processTitle: string;
    processDesc: string;
    processFlow: string[];
  };
  investors: {
    badge: string;
    title: string;
    whyTitle: string;
    whyPoints: { title: string; desc: string }[];
    sampleBadge: string;
    exampleTitle: string;
    exampleDesc: string;
    sampleCapacityLabel: string;
    sampleCapacityVal: string;
    sampleProductionLabel: string;
    sampleProductionVal: string;
    sampleCapexLabel: string;
    sampleCapexVal: string;
    sampleRevenueLabel: string;
    sampleRevenueVal: string;
    sampleIrrBadge: string;
    sample12YearNetLabel?: string;
    sample12YearNetVal?: string;
    sample12YearYieldBadge?: string;
    viewTableBtn?: string;
    hideTableBtn?: string;
    tableFootnote?: string;
    tableHeaders?: {
      year: string;
      generation: string;
      tariff: string;
      grossBilling: string;
      unisolarShare: string;
      investorShare: string;
      profitTax: string;
      investorNet: string;
      yield: string;
    };
    protectionTitle: string;
    protectionDesc: string;
    protectionPoints: string[];
    processTitle: string;
    processSteps: { title: string; desc: string }[];
    auditTitle: string;
    auditDesc: string;
    ctaButton: string;
  };
  solar3d: {
    badge: string;
    title: string;
    subtitle: string;
    modeSingle: string;
    modeArray: string;
    modeExploded: string;
    modeTracker: string;
    timeOfDay: string;
    tiltAngle: string;
    optimalTilt: string;
    setOptimal: string;
    optimalBadge: string;
    weatherCondition: string;
    weatherSunny: string;
    weatherCloudy: string;
    weatherSoiled: string;
    cleanPanels: string;
    washingLabel: string;
    cleaningDone: string;
    currentOutput: string;
    irradiance: string;
    efficiency: string;
    cellTemp: string;
    dailyEst: string;
    co2Offset: string;
    resetCamera: string;
    autoRotate: string;
    viewFront: string;
    viewSide: string;
    viewRear: string;
    specsTitle: string;
    moduleAnatomy: string;
    sunriseLabel: string;
    peakLabel: string;
    sunsetLabel: string;
    layerLabels: {
      glass: string;
      evaTop: string;
      cells: string;
      evaBottom: string;
      backsheet: string;
      frame: string;
      jbox: string;
    };
  };
  services: {
    badge: string;
    title: string;
    scopeTitle: string;
    calloutTitle: string;
    calloutDesc: string;
    calloutBtn: string;
    epcTitle: string;
    epcDesc: string;
    epcFeatures: string[];
    omTitle: string;
    omDesc: string;
    omFeatures: string[];
    carportsTitle: string;
    carportsDesc: string;
    carportsFeatures: string[];
  };
  contact: {
    badge: string;
    title: string;
    subtitle: string;
    deskTitle: string;
    deskDesc: string;
    addressLabel: string;
    addressValue: string;
    phoneLabel: string;
    emailLabel: string;
    tinLabel: string;
    socialLabel: string;
    formHeading: string;
    formName: string;
    formEmail: string;
    formPhone: string;
    formMsg: string;
    formSubmit: string;
    formSuccess: string;
    sendAnother: string;
    interestPrefill: string;
  };
  investorZone: {
    badge: string;
    title: string;
    subtitle: string;
    loginBtn: string;
    logoutBtn: string;
    encryptedTitle: string;
    encryptedDesc: string;
    keyLabel: string;
    passPlaceholder: string;
    hintTitle: string;
    hintText: string;
    wrongPass: string;
    welcome: string;
    portfolioId: string;
    secureActive: string;
    tabLiveTelemetry: string;
    tabDisbursements: string;
    tabDocuments: string;
    currentOutput: string;
    liveGeneration: string;
    activeFacilityNote: string;
    facilityTemp: string;
    gridFrequency: string;
    inverterStatus: string;
    cumulativeTitle: string;
    cumulativeDesc: string;
    totalCo2Savings: string;
    totalCashPaid: string;
    monthlyDist: string;
    auditedBy: string;
    monthCol: string;
    generationCol: string;
    revenueCol: string;
    payoutCol: string;
    statusCol: string;
    verified: string;
    docsTitle: string;
    docs: {
      title: string;
      desc: string;
      btnText: string;
    }[];
  };
  riskMatrix?: {
    badge: string; title: string; subtitle: string; footnote: string;
    legendEpc: string; legendUnisolar: string; legendOfftaker: string;
    legendShared: string; legendInvestor: string;
    r1Risk: string; r1Owner: string; r1Mit: string;
    r2Risk: string; r2Owner: string; r2Mit: string;
    r3Risk: string; r3Owner: string; r3Mit: string;
    r4Risk: string; r4Owner: string; r4Mit: string;
    r5Risk: string; r5Owner: string; r5Mit: string;
    r6Risk: string; r6Owner: string; r6Mit: string;
    r7Risk: string; r7Owner: string; r7Mit: string;
    r8Risk: string; r8Owner: string; r8Mit: string;
  };
  theCase?: {
    badge: string; title: string; subtitle: string;
    arg1Title: string; arg1Desc: string;
    arg2Title: string; arg2Desc: string;
    arg3Title: string; arg3Desc: string;
    arg4Title: string; arg4Desc: string;
    ctaBadge: string; ctaTitle: string; ctaDesc: string;
    ctaStir: string; ctaBtn: string; ctaBtnSecondary: string;
  };
  delivery?: {
    badge: string; title: string; subtitle: string;
    m1Day: string; m1Label: string; m1Desc: string;
    m2Day: string; m2Label: string; m2Desc: string;
    m3Day: string; m3Label: string; m3Desc: string;
    m4Day: string; m4Label: string; m4Desc: string;
    m5Day: string; m5Label: string; m5Desc: string;
    m6Day: string; m6Label: string; m6Desc: string;
    thenBadge: string; thenTitle: string;
    thenPoint1: string; thenPoint2: string; thenPoint3: string;
  };
  returns?: {
    badge: string; title: string; subtitle: string;
    kpi1Label: string; kpi1Value: string; kpi1Note: string;
    kpi2Label: string; kpi2Value: string; kpi2Note: string;
    kpi3Label: string; kpi3Value: string; kpi3Note: string;
    chartBadge: string; chartTitle: string;
    legendSolar: string; legendBank: string;
    bankLine: string; tooltipLabel: string; chartNote: string;
    paybackTitle: string; paybackDesc: string;
    escalationTitle: string; escalationDesc: string;
  };
  mechanism?: {
    badge: string;
    title: string;
    subtitle: string;
    stepLabel: string;
    expandHint: string;
    collapseHint: string;
    step1Label: string;
    step1Sub: string;
    step1Detail: string;
    conn1: string;
    step2Label: string;
    step2Sub: string;
    step2Detail: string;
    conn2: string;
    step3Label: string;
    step3Sub: string;
    step3Detail: string;
    conn3: string;
    step4Label: string;
    step4Sub: string;
    step4Detail: string;
    splitBadge: string;
    splitTitle: string;
    split20Label: string;
    split20Desc: string;
    split80Label: string;
    split80Desc: string;
    investorLabel: string;
    alignedNote1: string;
    alignedNote2: string;
    footnote: string;
  };
  footer: {
    tagline: string;
    legalSummary: string;
    motto: string;
    navTitle: string;
    contactTitle: string;
    allRights: string;
    bottomPpa: string;
  };
}
